numbers = list(range(1,11))
print(f' Original list: {numbers}')
print(f" First three: {numbers[0:3]}")
print(f" Last three: {numbers[-3:]}")
print(f" From second to before last: {numbers[1:-1]}")
print()

letters = list('abcdefgh')
print(f'Original letters: {letters}')
print(f"Every second letter from first: {letters[::2]}")
print(f"Every second letter from second: {letters[1::2]}")
print(f"From end to beginning: {letters[::-1]}")
print()

name = ('Python Programming')
print(f"Original name: {name}")
print(f"First word: {name[0:6]}")
print(f"Second word: {name[7:]}")
print(f"Every second letter: {name[::2]}")
print()

numbers_2 = list(range(1,11))
print(f"Original list: {numbers_2}")
print(f"Numbers from index 3 to 7: {numbers_2[3:7]}")
print(f"Last four numbers: {numbers_2[-4:]}")
print(f"Reverse list: {numbers_2[::-1]}")
print()

num_3 = tuple(range(1,10))
print(f"Original tuple: {num_3}")
print(f"Elements from 4 to end: {num_3[3:]}")
print(f"Numbers from beginning to 5: {num_3[:5]}")
print(f"Numbers without first and last: {num_3[1:-1]}")